### PR TITLE
fix: do not block in `accept`

### PR DESCRIPTION
**Pull request by c-cube**
cc @vphantom ?

### CODE REVIEW

**Comment by vphantom** [comment]
You no longer enforce a maximum number of concurrent connections?

**Comment by vphantom** [comment]
Sorry sorry, I was just looking at the diff lines.  I guess you're changing your multi-threading strategy if you're going from blocking to non-blocking there.  I don't really know what I should be evaluating here.

**Comment by c-cube** [comment]
Oh it's only the accept loop that uses select, so that it's not blocked forever in case we want to stop the server. In particular, `stop` should now work after 1s even if no new client connects.

**Comment by vphantom** [comment]
Oh! I forgot that the graceful shutdown was still an issue. (I've been neck-deep in unrelated work for so long…) For sure stopping the accept loop as soon as the signal is received, and not after the next client is accepted, is a much more predictable behavior.

**Pull request closed without merging**
