### PR TITLE
Wip nonblock

### PR DESCRIPTION
**Pull request by craff**
Fix non blocking write ... more work to be done before merge

### CODE REVIEW

**Comment by craff** [comment]
a PR on the wip-nonblock branch containing
- a merge of master
- a fix of your test (kill %1 not working on my machine)
- a first working non blocking buffered write (according to test)
- buffer (read and write) have size of the socket buffer
- needs cleanup before merge

**Comment by craff** [comment]
I do not understand: active_connections is not in this branch while I see the patched about it ???

**Comment by craff** [comment]
This branch seems now ok for my application but likely useless ... we can use timeout on socket to do the same
in a much simpler way, probably.

**Comment by c-cube** [comment]
> This branch seems now ok for my application but likely useless ... we can use timeout on socket to do the same in a much simpler way, probably.

Oh that's a very good idea actually. Would be much simpler.

**Comment by c-cube** [comment]
since we merged #30 I think this is unecessary?

**Comment by craff** [comment]
Clearly, you can delete wipnonblock. I do not see a reason to keep it. 

Le 12 décembre 2021 12:38:34 GMT-10:00, Simon Cruanes ***@***.***> a écrit :

**Pull request closed without merging**
