### PR TITLE
Post request

### PR DESCRIPTION
**Pull request by craff**
Added a function to parse post method request

### CODE REVIEW

**Comment by c-cube** [comment]
Very first reaction:

- if it has dependencies, it should be in a different library :-). I like that tiny-httpd doesn't pull anything.
- if we pull dependencies, Re is strictly better than Str. Str should never be used.

**Comment by craff** [comment]
I fixed .opam for the test to have a chance to pass.

I do not use very much regexp here, but it still makes life a bit easier. 

I actually started rewriting every thing using String only ... But stopped, it was getting too big or I was too lazy;-)

If you think Str is outside of stdlib ... And I am really unhappy to use a mutex here anyway. So the choice is

- Re (or another lib)
- write by hand

I would favor reducing dependency over C code for security reason (ideally, I would like to have a server only depending
on glibc)

**Comment by c-cube** [comment]
I honestly have no idea what's the simplest. Even using a small library of parser combinators could do the trick (I think you have one? I do, too).

We need to reframe this. I think this really should be a small web framework on top of tiny_httpd, but you don't need this for the httpd itself (which can be used for other stuff, like pure JSON APIs, or some sort of RPC, etc. without truly being a website).

If you want examples of how I've been using tiny-httpd I could show you some code, btw. I've mostly used tyxml and sqlite.

**Comment by craff** [comment]
No problem keep this code in my server side ! I just pushed the PR for you to see the code. 

And yes, I have a perser combinator lib ... But opam is really much more that just parser combinator, actually the user never sees the combinator. I was considering allowing compilation of the combinator to match menhir speed too, the combinator are composed at runtime currently, which is nice for self-extensible grammar, but useless for more application.

**Comment by craff** [comment]
It allowed me to clean my code which is always good ;-)

**Pull request closed without merging**
